POST http://49.234.156.101:7777/user/login
Content-Type: application/json

{
  "username": "hello",
  "password": "www"
}

###
POST http://49.234.156.101:7777/user/machineList
Content-Type: application/json

{
  "userid": 1
}

###
POST http://49.234.156.101:7777/user/oneMachineInfo
Content-Type: application/json

{
  "machineid": 1,
  "machineNum": "a",
  "flag": 1,
  "nowTime": "2021-08-21 18:12:24"
}

###
POST http://49.234.156.101:7777/user/oneOutputList
Content-Type: application/json

{
  "machineIdAndNum":
    {
      "machineNum": "a",
      "machineid": 1
    }
  ,
  "flag": 0,
  "nowTime": "2021-08-21 17:37:46"
}

###
POST http://49.234.156.101:7777/user/upUserInfo
Content-Type: application/json

{
"userid": 1,
"flag": 1,
"nowTime": "2021-08-21 18:12:24"
}

###
POST http://49.234.156.101:7777/user/mainpageOutputList
Content-Type: application/json

{
  "userid":1,
  "flag": 0,
  "nowTime": "2021-08-21 17:37:46"
}

###
POST http://49.234.156.101:7777/user/nowUserOutputSum
Content-Type: application/json

{
  "userid":1,
  "flag": 0,
  "nowTime": "2021-08-21 17:37:46"
}

###
POST http://49.234.156.101:7777/user/nowMachineOutputSum
Content-Type: application/json

{
  "machineid":1,
  "flag": 3,
  "nowTime": "2021-9-1 00:00:00"
}



###新增influxdb数据库数据
GET http://49.234.156.101:7777/index


###新增influxdb数据库数据
GET http://49.234.156.101:7777/test
