spring:
  influx:
    url: http://localhost:8086
    user: root
    password: 12345678
    database: novaInfluxdb
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/novasql?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        event:
          merge:
            entity_copy_observer: allow
        naming:
         # implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 7777
  # SSL证书配置
  servlet:
    context-path: /
  ssl:
    enabled: true
#    这个路径是服务器存放nova.p12的路径，不要修改
    key-store: C:/MyProject/nova.p12
#    key-store: src/main/resources/nova.p12 # （密钥文件路径，也可以配置绝对路径）
    key-store-password: 123456 # （密钥生成时输入的密钥库口令）
    key-store-type: PKCS12 #（密钥类型，与密钥生成命令一致）
    key-alias: tomcat #（密钥别名，与密钥生成命令一致）

#http: # 新加一个http的端口号配置
#  port: 8080